// Static detail paths are generated by the publisher, never supplied by a wallet.
export function publishedDetailPath(manifest, key, generation) {
  if (manifest?.generation !== generation) return null;
  const path = manifest?.files?.[key];
  return typeof path === "string" && /^data\/token-details\/[a-f0-9]{64}\.json$/.test(path)
    ? path : null;
}

export async function loadTokenDetail({manifest, key, generation, baseUrl, fetcher, accepts}) {
  const path = publishedDetailPath(manifest, key, generation);
  const urls = [path, baseUrl && `${baseUrl}/api/dashboard/token?token_key=${encodeURIComponent(key)}`].filter(Boolean);
  let lastError = new Error("No wallet detail source is available");
  for (const url of urls) {
    try {
      const response = await fetcher(url, {cache:"no-store", headers:{accept:"application/json"}});
      const detail = await response.json();
      if (!response.ok || !detail?.ok) throw new Error(detail?.error || `token detail ${response.status}`);
      if (!accepts(detail)) throw new Error("Details belong to an older snapshot. The newer scan summary is retained.");
      return detail;
    } catch (error) { lastError = error; }
  }
  throw lastError;
}
